assets:
  sources:
    - _assets/images
    - _assets/stylesheets

baseurl: /

exclude:
  - .scss-lint.yml
  - .csscomb.json
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin/*

ga_analytics: UA-28631876-4

gems:
  - jekyll-assets
  - jekyll-sitemap

permalink: pretty

url: http://stacss.nielsenramon.com
