permalink: pretty

exclude:
  - .scss-lint.yml
  - .csscomb.json
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin/*

assets:
  sources:
    - _assets/images
    - _assets/stylesheets

url: http://stacss.nielsenramon.com

ga_analytics: UA-28631876-4

gems:
  - jekyll-assets
  - jekyll-sitemap
